---
- name: checking if tmp directory exists or not
  stat:
    path: /root/DownloadDirector/WASv80
  register: tmp_file

- name: creating a tmp download directory
  file:
    path: /root/DownloadDirector/WASv80
    state: directory
  when: not tmp_file.stat.exists

- name: downloading and unzipping WASv80 ND 1 of 4
  unarchive:
    src: http://9.46.75.132/WASv80/WAS_NETWORK_DEPLOYMENT_V8.0_1_OF_4.zip
    dest: /root/DownloadDirector/WASv80/
    remote_src: yes
  when: "'com.ibm.websphere.ND.v80' not in imcl_listInstalledPackages.stdout"

- name: downloading and unzipping WASv80 ND 2 of 4
  unarchive:
    src: http://9.46.75.132/WASv80/WAS_NETWORK_DEPLOYMENT_V8.0_2_OF_4.zip
    dest: /root/DownloadDirector/WASv80/
    remote_src: yes
  when: "'com.ibm.websphere.ND.v80' not in imcl_listInstalledPackages.stdout"

- name: downloading and unzipping WASv80 ND 3 of 4
  unarchive:
    src: http://9.46.75.132/WASv80/WAS_NETWORK_DEPLOYMENT_V8.0_3_OF_4.zip
    dest: /root/DownloadDirector/WASv80/
    remote_src: yes
  when: "'com.ibm.websphere.ND.v80' not in imcl_listInstalledPackages.stdout"

- name: downloading and unzipping WASv80 ND 4 of 4
  unarchive:
    src: http://9.46.75.132/WASv80/WAS_NETWORK_DEPLOYMENT_V8.0_4_OF_4.zip
    dest: /root/DownloadDirector/WASv80/
    remote_src: yes
  when: "'com.ibm.websphere.ND.v80' not in imcl_listInstalledPackages.stdout"

- name: installing WAS v80
  shell: /opt/IBM/InstallationManager/eclipse/tools/imcl install com.ibm.websphere.ND.v80_8.0.0.20110503_0200 -repositories /root/DownloadDirector/WASv80 -installationDirectory /opt/IBM/WebSphere/AppServer80ND -acceptLicense -installFixes none
  when: "'com.ibm.websphere.ND.v80' not in imcl_listInstalledPackages.stdout"


- name: checking if tmp directory exists or not
  stat:
    path: /root/DownloadDirector/WASv80S
  register: tmp_file2

- name: creating a tmp download directory
  file:
    path: /root/DownloadDirector/WASv80S
    state: directory
  when: not tmp_file2.stat.exists

- name: downloading and unzipping WASv80 Supl 1 of 4
  unarchive:
    src: http://9.46.75.132/WASv80S/WASV8.0_SUPPL_1_OF_4_MP_ML.zip
    dest: /root/DownloadDirector/WASv80S/
    remote_src: yes
  when: "'com.ibm.websphere.ND.v80' not in imcl_listInstalledPackages.stdout"

- name: downloading and unzipping WASv80 Supl 2 of 4
  unarchive:
    src: http://9.46.75.132/WASv80S/WAS_V8.0_SUPPL_2_OF_4_MP_ML.zip
    dest: /root/DownloadDirector/WASv80S/
    remote_src: yes
  when: "'com.ibm.websphere.ND.v80' not in imcl_listInstalledPackages.stdout"

- name: downloading and unzipping WASv80 Supl 3 of 4
  unarchive:
    src: http://9.46.75.132/WASv80S/WAS_V8.0_SUPPL_3_OF_4_MP_ML.zip
    dest: /root/DownloadDirector/WASv80S/
    remote_src: yes
  when: "'com.ibm.websphere.ND.v80' not in imcl_listInstalledPackages.stdout"

- name: downloading and unzipping WASv80 Supl 4 of 4
  unarchive:
    src: http://9.46.75.132/WASv80S/WASV8.0_SUPPL_4_OF_4_MP_ML.zip
    dest: /root/DownloadDirector/WASv80S/
    remote_src: yes
  when: "'com.ibm.websphere.ND.v80' not in imcl_listInstalledPackages.stdout"


- name: installing IHS v80
  shell: /opt/IBM/InstallationManager/eclipse/tools/imcl install com.ibm.websphere.IHS.v80_8.0.0.20110503_0200 -repositories /root/DownloadDirector/WASv80S -installationDirectory /opt/IBM/HTTPServer80 -acceptLicense -installFixes none -properties "user.ihs.httpPort=80,user.ihs.allowNonRootSilentInstall=true"
  when: "'com.ibm.websphere.IHS.v80' not in imcl_listInstalledPackages.stdout"

- name: installing Plugin v80
  shell: /opt/IBM/InstallationManager/eclipse/tools/imcl install com.ibm.websphere.PLG.v80_8.0.0.20110503_0200 -repositories /root/DownloadDirector/WASv80S -installationDirectory /opt/IBM/WebSphere/Plugins80 -acceptLicense -installFixes none
  when: "'com.ibm.websphere.PLG.v80' not in imcl_listInstalledPackages.stdout"

- name: installing WCT v80
  shell: /opt/IBM/InstallationManager/eclipse/tools/imcl install com.ibm.websphere.WCT.v80_8.0.0.20110503_0200 -repositories /root/DownloadDirector/WASv80S -installationDirectory /opt/IBM/WebSphere/Toolbox80 -acceptLicense -installFixes none
  when: "'com.ibm.websphere.WCT.v80' not in imcl_listInstalledPackages.stdout"

- name: installing APPCLIENT v80
  shell: /opt/IBM/InstallationManager/eclipse/tools/imcl install com.ibm.websphere.APPCLIENT.v80_8.0.0.20110503_0200 -repositories /root/DownloadDirector/WASv80S -installationDirectory /opt/IBM/WebSphere/AppClient80 -acceptLicense -installFixes none -properties "user.appclient.serverHostname=localhost,user.appclient.serverPort=2809"
  when: "'com.ibm.websphere.APPCLIENT.v80' not in imcl_listInstalledPackages.stdout"




- name: checking if tmp directory exists or not
  stat:
    path: /root/DownloadDirector/WASv80FP15
  register: tmp_file

- name: creating a tmp download directory
  file:
    path: /root/DownloadDirector/WASv80FP15
    state: directory
  when: not tmp_file.stat.exists

- name: downloading and unzipping WASv80 1 of 2
  unarchive:
    src: http://9.46.75.132/WASv80FP15/8.0.0-WS-WAS-FP015-part1.zip
    dest: /root/DownloadDirector/WASv80FP15/
    remote_src: yes
  when: not tmp_file.stat.exists

- name: downloading and unzipping WASv80 2 of 2
  unarchive:
    src: http://9.46.75.132/WASv80FP15/8.0.0-WS-WAS-FP015-part2.zip
    dest: /root/DownloadDirector/WASv80FP15/
    remote_src: yes
  when: not tmp_file.stat.exists

- name: updating WAS v80
  shell: /opt/IBM/InstallationManager/eclipse/tools/imcl install com.ibm.websphere.ND.v80 -repositories /root/DownloadDirector/WASv80FP15 -installationDirectory /opt/IBM/WebSphere/AppServer80ND -acceptLicense 
  when: "'com.ibm.websphere.ND.v80' not in imcl_listInstalledPackages.stdout"


- name: checking if tmp directory exists or not
  stat:
    path: /root/DownloadDirector/WASv80FP15S
  register: tmp_file

- name: creating a tmp download directory
  file:
    path: /root/DownloadDirector/WASv80FP15S
    state: directory
  when: not tmp_file.stat.exists

- name: downloading and unzipping WASv80 Sup 1 of 2
  unarchive:
    src: http://9.46.75.132/WASv80FP15S/8.0.0-WS-WASSupplements-FP015-part1.zip
    dest: /root/DownloadDirector/WASv80FP15S/
    remote_src: yes
  when: not tmp_file.stat.exists

- name: downloading and unzipping WASv80 Sup 2 of 2
  unarchive:
    src: http://9.46.75.132/WASv80FP15S/8.0.0-WS-WASSupplements-FP015-part2.zip
    dest: /root/DownloadDirector/WASv80FP15S/
    remote_src: yes
  when: not tmp_file.stat.exists

- name: updating IHS v80
  shell: /opt/IBM/InstallationManager/eclipse/tools/imcl install com.ibm.websphere.IHS.v80 -repositories /root/DownloadDirector/WASv80FP15S -installationDirectory /opt/IBM/HTTPServer80 -acceptLicense 
  when: "'com.ibm.websphere.IHS.v80' not in imcl_listInstalledPackages.stdout"

- name: updating Plugin v80
  shell: /opt/IBM/InstallationManager/eclipse/tools/imcl install com.ibm.websphere.PLG.v80 -repositories /root/DownloadDirector/WASv80FP15S -installationDirectory /opt/IBM/WebSphere/Plugins80 -acceptLicense
  when: "'com.ibm.websphere.PLG.v80' not in imcl_listInstalledPackages.stdout"


- name: checking if tmp directory exists or not
  stat:
    path: /root/DownloadDirector/WASv80FP15WCT
  register: tmp_file

- name: creating a tmp download directory
  file:
    path: /root/DownloadDirector/WASv80FP15WCT
    state: directory
  when: not tmp_file.stat.exists

- name: downloading and unzipping WASv80 WCT
  unarchive:
    src: http://9.46.75.132/WASv80FP15WCT/8.0.0-WS-WCT-FP015.zip
    dest: /root/DownloadDirector/WASv80FP15WCT/
    remote_src: yes
  when: not tmp_file.stat.exists

- name: updating WCT v80
  shell: /opt/IBM/InstallationManager/eclipse/tools/imcl install com.ibm.websphere.WCT.v80 -repositories /root/DownloadDirector/WASv80FP15WCT -installationDirectory /opt/IBM/WebSphere/Toolbox80 -acceptLicense 
  when: "'com.ibm.websphere.WCT.v80' not in imcl_listInstalledPackages.stdout"

- name: updating APPCLIENT v80
  shell: /opt/IBM/InstallationManager/eclipse/tools/imcl install com.ibm.websphere.APPCLIENT.v80 -repositories /root/DownloadDirector/WASv80FP15S -installationDirectory /opt/IBM/WebSphere/AppClient80 -acceptLicense 
  when: "'com.ibm.websphere.APPCLIENT.v80' not in imcl_listInstalledPackages.stdout"

...
